class RecipeModel {
  final String id;
  String title, writer, description;
  int cookingTime;
  int servings;
  List<String> ingredients = [];
  String imgPath;
  RecipeModel({
    required this.id,
    required this.title,
    required this.writer,
    required this.description,
    required this.cookingTime,
    required this.servings,
    required this.imgPath,
    required this.ingredients,
  });
  static List<RecipeModel> demoRecipe = [
    RecipeModel(
      id: '1',
      title: 'Gruyère, Bacon, and Spinach Scrambled Eggs',
      writer: "Rosie Nguyen",
      description:
          'A touch of Dijon mustard, salty bacon, melty cheese, and a handful of greens seriously upgrades scrambled eggs, without too much effort!',
      cookingTime: 10,
      servings: 4,
      imgPath: 'assets/images/img1.jpg',
      ingredients: [
        '8 large eggs',
        '1 tsp. Dijon mustard',
        'Kosher salt and pepper',
        '1 tbsp. olive oil or unsalted butter',
        '2 slices thick-cut bacon, cooked and broken into pieces',
        '2 c. spinach, torn',
        '2 oz. Gruyère cheese, shredded',
      ],
    ),
    RecipeModel(
      id: '2',
      title: 'Classic Omelet and Greens',
      writer: "Zachary Chen",
      description:
          'Sneak some spinach into your morning meal for a boost of nutrients to start your day off right.',
      cookingTime: 10,
      servings: 4,
      imgPath: 'assets/images/img2.jpg',
      ingredients: [
        '4 large eggs',
        '1/4 cup milk',
        'Salt and pepper to taste',
        '1 tbsp. olive oil',
        '1 cup spinach, chopped',
        '1/2 cup shredded cheese',
      ],
    ),
    RecipeModel(
      id: '3',
      title: 'Sheet Pan Sausage and Egg Breakfast Bake',
      writer: "Imran Sefat",
      description:
          'A hearty breakfast that easily feeds a family of four, all on one sheet pan? Yes, please.',
      cookingTime: 30,
      servings: 4,
      imgPath: 'assets/images/img3.jpg',
      ingredients: [
        '4 sausages',
        '8 large eggs',
        '1 bell pepper, sliced',
        '1 onion, sliced',
        '1 cup cherry tomatoes',
        'Salt and pepper to taste',
        '1 tbsp. olive oil',
      ],
    ),
    RecipeModel(
      id: '4',
      title: 'Shakshuka',
      writer: "Sophia Bella",
      description:
          'Just wait til you break this one out at the breakfast table: sweet tomatoes, runny yolks, and plenty of toasted bread for dipping.',
      cookingTime: 20,
      servings: 4,
      imgPath: 'assets/images/img4.jpg',
      ingredients: [
        '1 tbsp. olive oil',
        '1 onion, chopped',
        '1 bell pepper, chopped',
        '2 cloves garlic, minced',
        '1 tsp. ground cumin',
        '1 tsp. paprika',
        '1/4 tsp. cayenne pepper',
        '1 can (28 oz) crushed tomatoes',
        '6 large eggs',
        'Salt and pepper to taste',
        'Fresh cilantro, chopped',
      ],
    ),
    RecipeModel(
      id: '5',
      title: 'Roast Lamb',
      writer: "John Doe",
      description:
          'A delicious roast lamb recipe that is perfect for any occasion.',
      cookingTime: 120,
      servings: 6,
      imgPath: 'assets/images/recipe1.jpg',
      ingredients: [
        '1 leg of lamb',
        '2 cloves garlic, minced',
        '1 tbsp. rosemary, chopped',
        'Salt and pepper to taste',
        '2 tbsp. olive oil',
        '1 cup red wine',
      ],
    ),
    RecipeModel(
      id: '6',
      title: 'Beef Steak',
      writer: "Jane Smith",
      description:
          'A classic beef steak recipe that is sure to impress.',
      cookingTime: 30,
      servings: 2,
      imgPath: 'assets/images/recipe2.jpg',
      ingredients: [
        '2 beef steaks',
        'Salt and pepper to taste',
        '2 tbsp. olive oil',
        '2 cloves garlic, minced',
        '1 sprig rosemary',
        '1 tbsp. butter',
      ],
    ),
    RecipeModel(
      id: '7',
      title: 'Chicken Curry',
      writer: "Alice Johnson",
      description:
          'A flavorful chicken curry recipe that is perfect for any meal.',
      cookingTime: 45,
      servings: 4,
      imgPath: 'assets/images/recipe3.jpg',
      ingredients: [
        '1 lb chicken breast, cubed',
        '1 onion, chopped',
        '2 cloves garlic, minced',
        '1 tbsp. curry powder',
        '1 can (14 oz) coconut milk',
        '1 cup chicken broth',
        'Salt and pepper to taste',
        '2 tbsp. olive oil',
      ],
    ),
    RecipeModel(
      id: '8',
      title: 'Sauteed Carrots',
      writer: "Bob Brown",
      description:
          'A simple and delicious sauteed carrots recipe.',
      cookingTime: 15,
      servings: 4,
      imgPath: 'assets/images/recipe4.jpg',
      ingredients: [
        '1 lb carrots, sliced',
        '2 tbsp. butter',
        '1 tbsp. honey',
        'Salt and pepper to taste',
        '1 tbsp. fresh parsley, chopped',
      ],
    ),
    RecipeModel(
      id: '9',
      title: 'Cereal Bars',
      writer: "Cathy Green",
      description:
          'A healthy and tasty cereal bars recipe.',
      cookingTime: 30,
      servings: 8,
      imgPath: 'assets/images/recipe5.jpg',
      ingredients: [
        '2 cups rolled oats',
        '1 cup peanut butter',
        '1/2 cup honey',
        '1/2 cup dried fruit',
        '1/4 cup chocolate chips',
      ],
    ),
    RecipeModel(
      id: '10',
      title: 'Fried Rice',
      writer: "David White",
      description:
          'A classic fried rice recipe that is quick and easy to make.',
      cookingTime: 20,
      servings: 4,
      imgPath: 'assets/images/recipe6.jpg',
      ingredients: [
        '2 cups cooked rice',
        '1 cup mixed vegetables',
        '2 eggs, beaten',
        '2 tbsp. soy sauce',
        '1 tbsp. sesame oil',
        '2 cloves garlic, minced',
        'Salt and pepper to taste',
      ],
    ),
    RecipeModel(
      id: '11',
      title: 'Garlic Shrimp',
      writer: "Eve Black",
      description:
          'A delicious garlic shrimp recipe that is perfect for seafood lovers.',
      cookingTime: 15,
      servings: 4,
      imgPath: 'assets/images/recipe7.jpg',
      ingredients: [
        '1 lb shrimp, peeled and deveined',
        '4 cloves garlic, minced',
        '2 tbsp. butter',
        '1 tbsp. lemon juice',
        'Salt and pepper to taste',
        '1 tbsp. fresh parsley, chopped',
      ],
    ),
    RecipeModel(
      id: '12',
      title: 'Cherry Pudding Cake',
      writer: "Frank Blue",
      description:
          'A delightful cherry pudding cake recipe that is perfect for dessert.',
      cookingTime: 60,
      servings: 8,
      imgPath: 'assets/images/recipe8.jpg',
      ingredients: [
        '1 cup flour',
        '1 cup sugar',
        '1/2 cup butter, melted',
        '1 cup milk',
        '1 tsp. vanilla extract',
        '1 can (21 oz) cherry pie filling',
      ],
    ),
    RecipeModel(
      id: '13',
      title: 'Snack Balls',
      writer: "Grace Yellow",
      description:
          'A healthy and tasty snack balls recipe.',
      cookingTime: 15,
      servings: 12,
      imgPath: 'assets/images/recipe9.jpg',
      ingredients: [
        '1 cup rolled oats',
        '1/2 cup peanut butter',
        '1/4 cup honey',
        '1/4 cup chocolate chips',
        '1/4 cup flax seeds',
      ],
    ),
    RecipeModel(
      id: '14',
      title: 'Classic Lamb Stew',
      writer: "Michael Green",
      description:
          'A hearty and comforting classic lamb stew.',
      cookingTime: 120,
      servings: 6,
      imgPath: 'assets/images/recipe10.jpg',
      ingredients: [
        '2 lbs lamb shoulder, cubed',
        '1 onion, chopped',
        '2 cloves garlic, minced',
        '2 carrots, sliced',
        '2 potatoes, cubed',
        '1 cup peas',
        '2 cups beef broth',
        '1 cup red wine',
        '2 tbsp. tomato paste',
        '1 tsp. thyme',
        'Salt and pepper to taste',
        '2 tbsp. olive oil',
      ],
    ),
    RecipeModel(
      id: '15',
      title: 'Spicy Honey Garlic Chicken Thighs',
      writer: "Sarah Brown",
      description:
          'Deliciously spicy and sweet honey garlic chicken thighs.',
      cookingTime: 40,
      servings: 4,
      imgPath: 'assets/images/recipe11.jpg',
      ingredients: [
        '8 chicken thighs',
        '1/4 cup honey',
        '1/4 cup soy sauce',
        '4 cloves garlic, minced',
        '1 tbsp. sriracha',
        '1 tbsp. olive oil',
        'Salt and pepper to taste',
      ],
    ),
    RecipeModel(
      id: '16',
      title: 'Beef Stroganoff',
      writer: "Emily White",
      description:
          'A creamy and savory beef stroganoff.',
      cookingTime: 30,
      servings: 4,
      imgPath: 'assets/images/recipe12.jpg',
      ingredients: [
        '1 lb beef sirloin, sliced',
        '1 onion, chopped',
        '2 cloves garlic, minced',
        '1 cup mushrooms, sliced',
        '1 cup beef broth',
        '1 cup sour cream',
        '2 tbsp. flour',
        '2 tbsp. butter',
        'Salt and pepper to taste',
        '2 tbsp. olive oil',
      ],
    ),
    RecipeModel(
      id: '17',
      title: 'Stir-Fried Mixed Vegetables in Soy Sauce',
      writer: "Linda Blue",
      description:
          'A quick and healthy stir-fried mixed vegetables in soy sauce.',
      cookingTime: 15,
      servings: 4,
      imgPath: 'assets/images/recipe13.jpg',
      ingredients: [
        '1 cup broccoli florets',
        '1 cup bell peppers, sliced',
        '1 cup snap peas',
        '1 cup carrots, sliced',
        '2 cloves garlic, minced',
        '2 tbsp. soy sauce',
        '1 tbsp. sesame oil',
        'Salt and pepper to taste',
      ],
    ),
    RecipeModel(
      id: '18',
      title: 'Granola with Nuts and Honey',
      writer: "Nancy Black",
      description:
          'A crunchy and sweet granola with nuts and honey.',
      cookingTime: 30,
      servings: 8,
      imgPath: 'assets/images/recipe14.jfif',
      ingredients: [
        '2 cups rolled oats',
        '1 cup mixed nuts',
        '1/2 cup honey',
        '1/4 cup coconut oil',
        '1 tsp. vanilla extract',
        '1/2 tsp. cinnamon',
      ],
    ),
    RecipeModel(
      id: '19',
      title: 'Baked Salmon',
      writer: "Oliver Green",
      description:
          'A simple and delicious baked salmon.',
      cookingTime: 20,
      servings: 4,
      imgPath: 'assets/images/recipe15.jpg',
      ingredients: [
        '4 salmon fillets',
        '2 cloves garlic, minced',
        '1 lemon, sliced',
        '1 tbsp. olive oil',
        'Salt and pepper to taste',
        '1 tbsp. fresh dill, chopped',
      ],
    ),
    RecipeModel(
      id: '20',
      title: 'Sour Stew',
      writer: "Paul White",
      description:
          'A tangy and flavorful sour stew.',
      cookingTime: 60,
      servings: 6,
      imgPath: 'assets/images/recipe16.jpg',
      ingredients: [
        '1 lb pork shoulder, cubed',
        '1 onion, chopped',
        '2 cloves garlic, minced',
        '2 cups sauerkraut',
        '1 cup beef broth',
        '1 cup sour cream',
        '2 tbsp. flour',
        '2 tbsp. butter',
        'Salt and pepper to taste',
        '2 tbsp. olive oil',
      ],
    ),
  ];
}
